### ISSUE TITLE
Missing feedback button

### ISSUE THREAD

**Issue by DoctorDoping** [filips123/GimVicUrnik#37]
There is no way to leave feedback in the pwa.

**Comment by ChristofferNorgaard** [comment]
Currently there is no plan to implement that, so for now, feedback will just be collected here.

**Comment by anaklusmos12** [comment]
ampak kako bom potem spammal slabe reviewe z ruskimi boti?

**Comment by anaklusmos12** [comment]
why are you gays?!?!?!?!

**Comment by anaklusmos12** [comment]
Black israelis from mossad congratulate alkaida and cia/fbi for bringing down 2 towers on 9/11. 5g causes cancer. vaccines are microchips, used to control the population in prepartion for the coming of a new world order. I know for a fact that this is a trait from people who have taken this so-called vaccine that has actual nanoparticles that attach to your DNA and they look like tiny little spiders and you can't get rid of them they act as receivers, so most of the areas that have more towers are getting sicker, and also people who have taken this so-called vaccine or shedding Spike proteins to the people who are unfaxed I have had this problem myself lately and I will not take that garbage shot that has the name of Lucifer patented as an enzyme in the so-called shots, so covid-19 basically stands for certification of vaccination identification and the 19 represents the first in the ninth letter of the alphabet Al artificial intelligence which is what this is nanotechnologies that are put in these vaccines that dehumanize us interns us into transhumanoids. This is no joke.

monkey pox, but the k is silent
